name: Trigger Matrix
on:
  workflow_dispatch:
    inputs:
      elements:
        description: 'Elements to matrix as comma separated list'
        required: true
        default: '1,2,3'
jobs:
  transform_input:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.transform_input.outputs.matrix }}
    steps:
      - name: Transform input
        id: transform_input
        run: |
          MATRIX=$(echo "${{ github.event.inputs.elements }}" | jq -Rsc '{ "id": . | gsub("\\n"; "") | split(",") }')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  trigger:
    needs: transform_input
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        run: |
          curl --request POST \
            --url https://api.github.com/repos/nomantis/triggered_greeting_receiving/actions/workflows/triggered_matrix.yml/dispatches \
            --header 'Accept: application/vnd.github+json' \
            --header 'Authorization: Bearer ${{ secrets.AUTH_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --header 'X-GitHub-Api-Version: 2022-11-28' \
            --data '{
              "ref": "master",
              "inputs": {
                "matrix": ${{ toJson(needs.transform_input.outputs.matrix) }}
              }
            }'
